name: todoooo
version: 1.0.0+1
publish_to: none
description: A new Flutter application.
environment: 
  sdk: '>=2.7.0 <3.0.0'

dependencies: 
  firebase_storage: 8.0.6
  flutter_slidable: 0.6.0
  flutter_switch: 0.3.1
  lottie: 1.0.1
  get_storage: 2.0.2
  auto_size_text: 2.1.0
  rounded_loading_button: 1.0.18
  firebase_core: 1.1.1
  cloud_firestore: 1.0.7
  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^8.11.0
  get: ^4.1.4
  circular_check_box: ^1.0.4
  animated_text_kit: ^3.1.0
  google_fonts: ^2.0.0
  local_auth: ^1.1.0
  image_picker: ^0.7.3
  image_cropper: ^1.4.0
  firebase_auth: ^1.0.3
  google_sign_in: ^5.0.1
  intl: 0.17.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - images/
  uses-material-design: true

